const { test } = require('node:test');
const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const { PGlite } = require('@electric-sql/pglite');
const actor='11111111-2222-4333-8444-555555555555', model='aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee', moduleId='bbbbbbbb-bbbb-4ccc-8ddd-eeeeeeeeeeee', corner='cccccccc-bbbb-4ccc-8ddd-eeeeeeeeeeee', version='dddddddd-bbbb-4ccc-8ddd-eeeeeeeeeeee';
test('asset ledger, archive/restore, pending uploads, canonical corner isolation and RLS are transactional', async t => {
  const db=new PGlite(); t.after(()=>db.close());
  await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
    create table profiles(id uuid primary key,role text); insert into profiles values('${actor}','admin');
    create table merchant_stores(id text,owner_id uuid,active boolean);
    create table kitchen_modules(id uuid primary key default gen_random_uuid(),code text unique,name text,cabinet_type text,width_mm int,height_mm int,depth_mm int,active boolean default true);
    create table furniture_models(id uuid primary key,product_id text,category text,dimensions_w numeric,dimensions_h numeric,dimensions_d numeric,store_ids jsonb,in_stock int default 5,base_price bigint default 100,colors jsonb default '[{"id":"oak","priceDelta":0}]',materials jsonb default '[{"id":"wood","priceDelta":0}]',updated_at timestamptz,
      processing_job_id uuid,processing_status text,processing_error text,processing_requested_at timestamptz,processing_updated_at timestamptz,
      source_glb_path text,glb_path text,preview_glb_path text,standard_glb_path text,thumbnail_path text);
    alter table furniture_models enable row level security; grant select on furniture_models to anon,authenticated;
    create table kitchen_module_variants(furniture_model_id uuid references furniture_models(id),module_id uuid references kitchen_modules(id),variant_code text,opening text,door_count int,drawer_count int,active boolean default true,configuration jsonb default '{}',unique(module_id,variant_code));
    alter table kitchen_module_variants enable row level security; grant select on kitchen_module_variants to anon,authenticated;
    create table orders(id uuid primary key default gen_random_uuid(),items jsonb,stock_reserved boolean default false);
    insert into kitchen_modules values('${moduleId}','BASE-1000','Base','base',1000,840,600,true),('${corner}','CORNER-BASE-1000','Corner','corner',1000,840,600,true);
    insert into furniture_models(id,category,dimensions_w,dimensions_h,dimensions_d,processing_status,glb_path) values('${model}','kitchen-cabinet',1,.84,.6,'ready','old-delivery.glb');
    insert into kitchen_module_variants(furniture_model_id,module_id,variant_code,opening,door_count,drawer_count) values('${model}','${moduleId}','BASE-1000-2-DOORS','doors',2,0);`);
  await db.exec(readFileSync('supabase/migrations/20261001131646_glb_cabinet_standard.sql','utf8'));
  await db.exec(readFileSync('supabase/migrations/20261001135110_cabinet_design_codes.sql','utf8'));
  await db.exec('create trigger reserve_order_stock before insert on orders for each row execute function reserve_order_stock()');
  await db.query("update furniture_models set product_id='test-cabinet' where id=$1",[model]);
  assert.equal((await db.query('select count(*)::int n from model_assets')).rows[0].n,1);
  await db.query('select set_model_archived($1,$2,true)',[actor,model]);
  const order=[{productId:'test-cabinet',qty:1,color:'oak',material:'wood',unitPrice:100}];
  await assert.rejects(db.query('insert into orders(items) values($1)',[order]),{code:'P0004'});
  await db.exec('set role anon');
  assert.equal((await db.query('select * from furniture_models')).rows.length,0);
  assert.equal((await db.query('select * from kitchen_module_variants')).rows.length,0);
  await assert.rejects(db.query('select * from model_assets'),{code:'42501'});
  await assert.rejects(db.query('select set_model_archived($1,$2,false)',[actor,model]),{code:'42501'});
  await db.exec('reset role');
  assert.equal((await db.query('select * from model_assets')).rows[0].storage_path,'old-delivery.glb');
  assert.equal((await db.query('select * from kitchen_module_variants')).rows.length,1);
  await assert.rejects(db.query('delete from furniture_models where id=$1',[model]),/Archive models/);
  await assert.rejects(db.query("update furniture_models set glb_path='new.glb' where id=$1",[model]),/read-only/);
  await db.query('select set_model_archived($1,$2,false)',[actor,model]);
  await db.query('insert into orders(items) values($1)',[order]);
  assert.equal((await db.query('select in_stock from furniture_models')).rows[0].in_stock,4);
  await assert.rejects(db.query('update kitchen_module_variants set module_id=$1 where furniture_model_id=$2',[corner,model]),/different module/);
  await assert.rejects(db.query("update kitchen_module_variants set variant_code='CORNER-BASE-1000-2-DOORS' where furniture_model_id=$1",[model]),/Canonical variant/);
  await db.query("insert into kitchen_module_variants(furniture_model_id,module_id,variant_code,opening,door_count,drawer_count,configuration) values($1,$2,'BASE-1000-2-DOORS-TOP144','doors',2,0,'{\"designCode\":\"TOP144\"}')",[model,moduleId]);
  assert.equal((await db.query('select count(*)::int n from kitchen_module_variants')).rows[0].n,2);
  await assert.rejects(db.query("update kitchen_module_variants set configuration='{\"designCode\":\"top144\"}' where variant_code='BASE-1000-2-DOORS-TOP144'"),/Canonical design/);
  await db.query("insert into model_assets(model_id,version_id,role,storage_path,byte_size,created_by) values($1,$2,'source','source.glb',100,$3)",[model,version,actor]);
  await db.query('select queue_model_asset($1,$2,$3,$4,$5)',[actor,model,'source.glb','a'.repeat(64),{standard:'cabinet-v1'}]);
  assert.equal((await db.query('select processing_status from furniture_models')).rows[0].processing_status,'queued');
  await db.query("update furniture_models set glb_path='new-delivery.glb',processing_status='ready',source_glb_path=null where id=$1",[model]);
  const assets=(await db.query('select storage_path,state from model_assets order by storage_path')).rows;
  assert.deepEqual(assets,[{storage_path:'new-delivery.glb',state:'available'},{storage_path:'old-delivery.glb',state:'retired'},{storage_path:'source.glb',state:'deleted'}]);
  await assert.rejects(db.query('select queue_model_asset($1,$2,$3,$4,$5)',[actor,model,'missing.glb','a'.repeat(64),{}]),/intent/);
  await assert.rejects(db.query('select set_model_archived(null,$1,true)',[model]),/Admin required/);
});
