const {test}=require('node:test');
const assert=require('node:assert/strict');
const {readFileSync}=require('node:fs');
const {randomUUID}=require('node:crypto');
const {PGlite}=require('@electric-sql/pglite');

test('Phase 4: merchant → review → publish → edited customer project → quote, private audit and render consent/quota',async t=>{
  const db=new PGlite();t.after(()=>db.close());
  await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
    create schema auth; create table auth.users(id uuid primary key);
    create table profiles(id uuid primary key references auth.users(id),role text not null);
    create table merchant_stores(id text primary key,owner_id uuid not null unique references auth.users(id),name text not null default 'Factory',store_type text not null,active boolean not null default true);
    create table furniture_models(id uuid primary key default gen_random_uuid(),category text not null,product_id text,name text not null default '',glb_path text,thumbnail_path text,dimensions_w numeric default 1,dimensions_h numeric default 1,dimensions_d numeric default 1,processing_status text default 'idle',created_at timestamptz default now(),constraint furniture_models_category_check check(category in ('sofa')));
    create table kitchen_garnitures(user_id uuid references auth.users(id),id uuid,name text default 'Kitchen',design jsonb not null,created_at timestamptz default now(),updated_at timestamptz default now(),primary key(user_id,id));`);
  for(const file of ['20260922023456_kitchen_marketplace_foundation','20260923024337_kitchen_ai_render_workflow','20260923032130_kitchen_project_thumbnails','20260923035533_kitchen_marketplace_version_editing','20260923060138_kitchen_review_notifications','20260923084924_clone_published_kitchen_design','20260924060214_kitchen_quote_requests','20261002063235_kitchen_marketplace_phase4','20261002073048_kitchen_marketplace_actor_lookup'])
    await db.exec(readFileSync(`supabase/migrations/${file}.sql`,'utf8'));
  const merchant=randomUUID(),other=randomUUID(),admin=randomUUID(),customer=randomUUID(),source=randomUUID();
  await db.query('insert into auth.users values($1),($2),($3),($4)',[merchant,other,admin,customer]);
  await db.query("insert into profiles values($1,'merchant'),($2,'merchant'),($3,'admin'),($4,'customer')",[merchant,other,admin,customer]);
  await db.query("insert into merchant_stores(id,owner_id,store_type) values('factory',$1,'factory'),('handmade',$2,'handmade')",[merchant,other]);
  const project={version:1,layout:'straight',room:{width:4000,depth:3000,height:2600},cabinets:[{id:'base',type:'base',width:600,height:820,depth:600,position:{x:300,y:0,z:300,rotation:0}}]};
  await db.query("insert into kitchen_garnitures(user_id,id,design,thumbnail_url) values($1,$2,$3,'https://res.cloudinary.com/demo/image/upload/source.webp')",[merchant,source,JSON.stringify(project)]);
  const payload={title:'Phase 4 test kitchen',pricingMode:'from',priceFrom:1000,priceTo:2000,materials:['Царс','MDF']};
  const create=async(slug='phase4-test')=>(await db.query('select create_kitchen_marketplace_design($1,$2,$3,$4) result',[merchant,source,slug,JSON.stringify(payload)])).rows[0].result;
  const created=await create(); const args=[merchant,created.designId,created.versionId];
  await db.query("update kitchen_garnitures set design=jsonb_set(design,'{room,width}','4250') where user_id=$1 and id=$2",[merchant,source]);
  await db.query("select save_kitchen_marketplace_version($1,$2,$3,'sync_project',$4)",[...args,JSON.stringify(payload)]);
  assert.equal((await db.query('select min_room_width_mm from kitchen_design_versions where id=$1',[created.versionId])).rows[0].min_room_width_mm,4250);
  assert.deepEqual((await db.query('select price_to,materials from kitchen_design_versions where id=$1',[created.versionId])).rows[0],{price_to:2000,materials:['Царс','MDF']});
  await db.query("select save_kitchen_marketplace_version($1,$2,$3,'edit',$4)",[...args,JSON.stringify({...payload,priceFrom:3000,priceTo:4000})]);
  assert.equal((await db.query('select price_to from kitchen_design_versions where id=$1',[created.versionId])).rows[0].price_to,4000);
  const media=(await db.query("select id from kitchen_design_media where version_id=$1 and status='ready' and is_primary",[created.versionId])).rows[0].id;
  const renderArgs=[...args,media,'Preserve the exact kitchen layout in daylight.','openai','test-model'];
  await assert.rejects(db.query('select request_kitchen_render($1,$2,$3,$4,$5,$6,$7)',renderArgs),{code:'P0017'});
  await assert.rejects(db.query('select request_kitchen_render($1,$2,$3,$4,$5,$6,$7,true)',[other,...renderArgs.slice(1)]),{code:'42501'});
  const request=async()=>(await db.query('select request_kitchen_render($1,$2,$3,$4,$5,$6,$7,true) id',renderArgs)).rows[0].id;
  const firstJob=await request();
  await assert.rejects(request(),{code:'P0011'});
  await assert.rejects(db.query('select submit_kitchen_design($1,$2,$3)',args),{code:'P0016'});
  await assert.rejects(db.query('select claim_kitchen_render($1,$2)',[merchant,firstJob]),{code:'42501'});
  await db.query('select cancel_kitchen_render($1,$2,$3)',[admin,firstJob,'Reference needs correction']);
  await assert.rejects(db.query('select claim_kitchen_render($1,$2)',[admin,firstJob]),{code:'P0002'});
  const secondJob=await request(); await db.query('select claim_kitchen_render($1,$2)',[admin,secondJob]);
  await db.query("select fail_kitchen_render($1,$2,'mock provider failure','{}')",[admin,secondJob]);
  assert.equal((await db.query('select metadata from kitchen_render_jobs where id=$1',[secondJob])).rows[0].metadata.consentVersion,'kitchen-ai-v1');
  const thirdJob=await request(); await db.query('select cancel_kitchen_render($1,$2,$3)',[merchant,thirdJob,'Cancel request']);
  await assert.rejects(request(),{code:'P0019'});
  assert.equal((await db.query('select read_kitchen_render_usage($1) usage',[merchant])).rows[0].usage.used,3);
  await db.query('select submit_kitchen_design($1,$2,$3)',args);
  await assert.rejects(db.query("select review_kitchen_design($1,$2,$3,'changes_requested','')",[admin,...args.slice(1)]),{code:'P0018'});
  await db.query("select review_kitchen_design($1,$2,$3,'changes_requested','Please describe materials')",[admin,...args.slice(1)]);
  await db.query('select submit_kitchen_design($1,$2,$3)',args);
  await db.query("select review_kitchen_design($1,$2,$3,'approved','Checked dimensions')",[admin,...args.slice(1)]);
  await assert.rejects(db.query('select publish_kitchen_design($1,$2,$3)',args),{code:'42501'});
  await assert.rejects(db.query("select review_kitchen_design($1,$2,$3,'published','')",[merchant,...args.slice(1)]),{code:'42501'});
  await db.query("select review_kitchen_design($1,$2,$3,'published','')",[admin,...args.slice(1)]);
  await db.exec('grant select(id,store_type,active,name) on public.merchant_stores to anon; set role anon');
  assert.equal((await db.query('select count(*)::int n from kitchen_designs')).rows[0].n,1);
  await db.exec('reset role');
  // Match the real app role: service_role cannot SELECT auth.users. Superuser-only
  // fixture execution would miss an invoker RPC's permission regression here.
  await db.exec('grant usage on schema auth to service_role; grant select,insert,update on profiles,merchant_stores,kitchen_garnitures,kitchen_designs,kitchen_design_versions,kitchen_design_media,kitchen_quote_requests,user_notifications to service_role; set role service_role');
  assert.equal((await db.query("select has_table_privilege(current_user,'auth.users','select') allowed")).rows[0].allowed,false);
  assert.deepEqual((await db.query('select read_customer_kitchen_quotes($1,0) result',[customer])).rows[0].result,[]);
  const customerProject=randomUUID();
  await db.query('select clone_published_kitchen_design($1,$2,$3)',[customer,created.designId,customerProject]);
  await db.query("update kitchen_garnitures set design=jsonb_set(design,'{room,width}','4500') where user_id=$1 and id=$2",[customer,customerProject]);
  const quote=(await db.query("select create_kitchen_quote_request($1,$2,$3,$4,$5,$6,'Changed the width') result",[customer,created.designId,customerProject,randomUUID(),JSON.stringify({name:'Customer',phone:'99112233',email:'test@example.com'}),JSON.stringify({widthMm:4500,depthMm:3000,heightMm:2600})])).rows[0].result.id;
  assert.equal((await db.query('select project_snapshot from kitchen_quote_requests where id=$1',[quote])).rows[0].project_snapshot.room.width,4500);
  await assert.rejects(db.query("select update_merchant_kitchen_quote($1,$2,'quoted','submitted',5000,'Quote')",[other,quote]),{code:'P0002'});
  await db.query("select update_merchant_kitchen_quote($1,$2,'quoted','submitted',5000,'Material and delivery included')",[merchant,quote]);
  assert.equal((await db.query('select read_customer_kitchen_quotes($1,0) result',[customer])).rows[0].result[0].quotedPrice,5000);
  assert.equal((await db.query('select read_merchant_kitchen_quotes($1,999,$2) result',[merchant,quote])).rows[0].result.length,0);
  assert.equal((await db.query('select read_merchant_kitchen_quotes($1,0,$2) result',[merchant,quote])).rows[0].result[0].id,quote);
  assert.deepEqual((await db.query('select read_merchant_kitchen_quotes($1,0,$2) result',[other,quote])).rows[0].result,[]);
  await db.query("update merchant_stores set active=false where id='factory'");
  await assert.rejects(db.query('select clone_published_kitchen_design($1,$2,$3)',[customer,created.designId,randomUUID()]),{code:'P0002'});
  await db.query("update merchant_stores set active=true where id='factory'");
  assert.equal((await db.query("select href from user_notifications where entity_id=$1 and user_id=$2 order by created_at limit 1",[quote,merchant])).rows[0].href,`/merchant?tab=quotes&quote=${quote}`);
  assert.equal((await db.query("select href from user_notifications where entity_id=$1 and user_id=$2 order by created_at desc limit 1",[quote,customer])).rows[0].href,`/account?quote=${quote}#kitchen-quotes`);
  await db.exec('reset role');
  const replacement=(await db.query("select save_kitchen_marketplace_version($1,$2,$3,'new_version',$4) result",[...args,JSON.stringify(payload)])).rows[0].result;
  assert.equal((await db.query('select published_version_id from kitchen_designs where id=$1',[created.designId])).rows[0].published_version_id,created.versionId);
  await db.query("select review_kitchen_design($1,$2,null,'suspended','Listing needs review')",[admin,created.designId]);
  await db.exec('set role anon');
  assert.equal((await db.query('select count(*)::int n from kitchen_designs')).rows[0].n,0);
  await db.exec('reset role');
  await assert.rejects(db.query('select publish_kitchen_design($1,$2,$3)',args),{code:'42501'});
  await assert.rejects(db.query('select submit_kitchen_design($1,$2,$3)',[merchant,created.designId,replacement.versionId]),{code:'42501'});
  await assert.rejects(db.query("select add_kitchen_design_media($1,$2,$3,'photo','https://res.cloudinary.com/demo/test.jpg','Test',false,100,100,'{}')",[merchant,created.designId,replacement.versionId]),{code:'P0012'});
  await db.query("select review_kitchen_design($1,$2,$3,'published','Review resolved')",[admin,...args.slice(1)]);
  const events=(await db.query('select action,actor_id,metadata from kitchen_marketplace_audit where design_id=$1',[created.designId])).rows;
  for(const action of ['design_created','version_edited','submitted','review_approved','published','suspended','render_cancelled','render_failed','quote_submitted','quote_quoted','customer_cloned']) assert.ok(events.some(e=>e.action===action),action);
  assert.ok(events.every(e=>e.actor_id && !('contact' in e.metadata)));
  await db.exec('set role anon');
  await assert.rejects(db.query('select * from kitchen_marketplace_audit'),{code:'42501'});
  await assert.rejects(db.query('select read_kitchen_render_usage($1)',[merchant]),{code:'42501'});
  await db.exec('reset role; set role service_role');
  await assert.rejects(db.query('delete from kitchen_marketplace_audit'),{code:'42501'});
  await db.exec('reset role');
  await db.query('select archive_kitchen_design($1,$2)',[merchant,created.designId]);
  await assert.rejects(db.query("select review_kitchen_design($1,$2,$3,'published','')",[admin,...args.slice(1)]),{code:'P0012'});
});
