const {test}=require('node:test');
const assert=require('node:assert/strict');
const {readFileSync}=require('node:fs');
const {randomUUID}=require('node:crypto');
const {PGlite}=require('@electric-sql/pglite');
const document={schemaVersion:1,design:{rooms:[{pieces:[]}],width:5}};
test('room project SQL CAS, operation retry, explicit import dedup, immutable history, archive and tenant permissions',async t=>{
  const db=new PGlite();t.after(()=>db.close());
  await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
    create schema auth;create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);
  await db.exec(readFileSync('supabase/migrations/20261003050000_room_cloud_projects.sql','utf8'));
  const a=randomUUID(),b=randomUUID(),id=randomUUID(),op=randomUUID();
  await db.query('insert into auth.users values($1),($2)',[a,b]);
  await db.exec('set role service_role');
  assert.equal((await db.query('select phase8_readiness() ready')).rows[0].ready,true);
  const save=async(actor,project,rev,doc=document,operation=randomUUID(),key=null,force=false)=>(await db.query('select save_room_project($1,$2,$3,$4,$5,$6,$7,$8) v',[actor,project,'Room',JSON.stringify(doc),rev,operation,key,force])).rows[0].v;
  const first=await save(a,id,0,document,op,'browser:old-room');assert.equal(first.project.revision,1);
  const changed={...document,design:{...document.design,width:6}};
  assert.equal((await save(a,id,1,changed)).project.revision,2);
  assert.equal((await save(a,id,0,document,op,'browser:old-room')).project.revision,1,'retry returns acknowledged snapshot even after a newer write');
  await assert.rejects(save(a,id,2,changed,op),{code:'22023'});
  await assert.rejects(save(a,id,1,document),{code:'40001'});
  const duplicate=await save(a,randomUUID(),0,document,randomUUID(),'browser:old-room');
  assert.equal(duplicate.alreadyImported,true);assert.equal(duplicate.project.id,id);
  assert.equal((await save(a,id,2,changed)).project.revision,2,'no-op does not duplicate history');
  assert.equal((await save(a,id,2,{...changed,design:{...changed.design,updatedAt:999}})).project.revision,2,'local save timestamp is not a content edit');
  assert.equal((await save(a,id,2,document,randomUUID(),null,true)).project.revision,3,'restore creates a new revision');
  await db.query('select archive_room_project($1,$2,3,true)',[a,id]);
  await assert.rejects(save(a,id,3,changed),{code:'55000'});
  assert.equal((await db.query('select count(*)::int n from room_project_versions')).rows[0].n,3);
  await db.query('select archive_room_project($1,$2,3,false)',[a,id]);
  assert.equal((await save(b,id,0)).project.revision,1,'same ID cannot overwrite another actor');
  await assert.rejects(db.query("update room_project_versions set name='forged'"),{code:'42501'});
  await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[a]);await db.exec('set role authenticated');
  assert.equal((await db.query('select count(*)::int n from room_projects')).rows[0].n,1);
  assert.equal((await db.query('select count(*)::int n from room_project_versions')).rows[0].n,3);
  await assert.rejects(save(a,id,3),{code:'42501'});
  await assert.rejects(db.query("update room_projects set name='forged'"),{code:'42501'});
  await db.exec('reset role;set role anon');await assert.rejects(db.query('select * from room_projects'),{code:'42501'});
});
test('archived room versions retain imported asset references in Phase 6 cleanup candidates',async t=>{
  const db=new PGlite();t.after(()=>db.close());
  await db.exec(readFileSync('tests/helpers/phase6-schema.sql','utf8'));
  await db.exec(`create schema auth;create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql as $$select null::uuid$$;`);
  for(const file of ['20261002150000_phase6_rate_limits.sql','20261002151000_phase6_storage_cleanup.sql','20261003050000_room_cloud_projects.sql','20261003051000_room_cleanup_references.sql'])
    await db.exec(readFileSync(`supabase/migrations/${file}`,'utf8'));
  const actor=randomUUID(),project=randomUUID(),asset=randomUUID(),path=`casa-nova/products/${randomUUID()}/${randomUUID()}`,url=`https://fixture.invalid/${path}`;
  await db.query('insert into auth.users values($1)',[actor]);
  await db.query("insert into product_media_assets(id,public_id,url,state,created_at) values($1,$2,$3,'failed',now()-interval '8 days')",[asset,path,url]);
  await db.exec('set role service_role');
  assert.equal((await db.query('select count(*)::int n from storage_cleanup_candidates(100)')).rows[0].n,1);
  await db.query('select save_room_project($1,$2,$3,$4,0,$5,null,false)',[actor,project,'Asset room',JSON.stringify({schemaVersion:1,design:{rooms:[{pieces:[{historicalImage:url}]}]}}),randomUUID()]);
  await db.query('select archive_room_project($1,$2,1,true)',[actor,project]);
  assert.equal((await db.query('select count(*)::int n from storage_cleanup_candidates(100)')).rows[0].n,0,'archive cannot orphan history images');
  assert.equal((await db.query('select claim_storage_cleanup($1,$2,$3) claimed',['image',asset,randomUUID()])).rows[0].claimed,false);
});
test('validated nested kitchen survives cloud SQL roundtrip and source edits without changing the historical millimetres or room metres',async t=>{
  const {loadSource}=require('./helpers/load-source.cjs'),{roomDocument,parseRoomProject}=loadSource('src/lib/roomProjectValidation.ts');
  const source=loadSource('src/lib/kitchenAssembly.ts').createUnifiedKitchen(),originalWidth=source.room.width;
  const doc=roomDocument({id:'d_import',name:'Room',size:'40',width:5,depth:4,wallColor:'#EFE6D6',floorColor:'#C9A37A',createdAt:1,updatedAt:1,
    pieces:[{instanceId:'imported',productId:'kitchen:source',x:1.25,z:.5,rotation:Math.PI/2,color:'#ddd8cc',material:'wood',kitchen:{id:'source',name:'Kitchen',design:source}}]});
  const db=new PGlite();t.after(()=>db.close());
  await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql as $$select null::uuid$$;`);
  await db.exec(readFileSync('supabase/migrations/20261003050000_room_cloud_projects.sql','utf8'));
  const actor=randomUUID(),id=randomUUID();await db.query('insert into auth.users values($1)',[actor]);await db.exec('set role service_role');
  await db.query('select save_room_project($1,$2,$3,$4,0,$5,null,false)',[actor,id,'Room',JSON.stringify(doc),randomUUID()]);
  source.room.width+=1000;
  const read=parseRoomProject((await db.query('select document from room_project_versions where user_id=$1 and project_id=$2 and revision=1',[actor,id])).rows[0].document);
  assert.equal(read.design.width,5);assert.equal(read.design.pieces[0].x,1.25);assert.equal(read.design.pieces[0].rotation,Math.PI/2);
  assert.equal(read.design.rooms[0].pieces[0].kitchen.design.room.width,originalWidth);
  const changed=structuredClone(doc);changed.design.name='Next room';
  await db.query('select save_room_project($1,$2,$3,$4,1,$5,null,false)',[actor,id,'Next room',JSON.stringify(changed),randomUUID()]);
  assert.deepEqual((await db.query('select document from room_project_versions where user_id=$1 and project_id=$2 and revision=1',[actor,id])).rows[0].document,doc);
});
